- name: "Snipe install | Download snipe release v{{ snipe_install_version }}"
  unarchive:
    src: "https://github.com/snipe/snipe-it/archive/v{{ snipe_install_version }}.zip"
    dest: "/opt"
    remote_src: yes
    mode: 0775
    owner: www-data
    group: www-data
    creates: "{{ snipe_install_dir }}-{{ snipe_install_version }}"
  become: true

- name: "Snipe install | Link downloaded file to {{ snipe_install_dir }}"
  file:
    src: "{{ snipe_install_dir }}-{{ snipe_install_version }}"
    dest: "{{ snipe_install_dir }}"
    state: link
    mode: 0775
    owner: www-data
    group: www-data
  become: true

- name: Snipe install | Change ownership
  file:
    path: "{{ snipe_install_dir }}-{{ snipe_install_version }}"
    owner: www-data
    group: www-data
    recurse: yes
  become: true

- name: Snipe install | Copy updated .env file to snipe-it directory
  template:
    src: dotenv.j2
    dest: "{{ snipe_install_dir }}/.env"
  become: true

- name: Snipe install | Copy updated nginx site config
  template:
    src: snipeit.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
  become: true
