- name: "Snipe install | Download snipe release v{{ snipe_install_version }}"
  unarchive:
    src: "https://github.com/snipe/snipe-it/archive/v{{ snipe_install_version }}.zip"
    dest: "/opt"
    remote_src: yes
    mode: 0775
    owner: www-data
    group: www-data
    creates: "{{ snipe_install_dir }}-{{ snipe_install_version }}"
  become: true

- name: "Snipe install | Link downloaded file to {{ snipe_install_dir }}"
  file:
    src: "{{ snipe_install_dir }}-{{ snipe_install_version }}"
    dest: "{{ snipe_install_dir }}"
    state: link
    mode: 0775
    owner: www-data
    group: www-data
  become: true

- name: Snipe install | Change ownership
  file:
    path: "{{ snipe_install_dir }}-{{ snipe_install_version }}"
    owner: www-data
    group: www-data
    recurse: yes
  become: true

- name: Snipe install | Copy updated .env file to snipe-it directory
  template:
    src: dotenv.j2
    dest: "{{ snipe_install_dir }}/.env"
  become: true

- name: Snipe install | Install php composer
  get_url:
    url: 'https://getcomposer.org/download/latest-1.x/composer.phar'
    dest: "{{ snipe_install_dir }}/composer.phar"
    mode: '0775'

- name: Snipe install | Install snipe dependencies
  command: php composer.phar global require hirak/prestissimo
  args:
    chdir: "{{ snipe_install_dir }}"
    creates: "{{ lookup('env','HOME') }}/.config/composer/vendor/hirak/prestissimo"
    warn: no
    
- name: Snipe install | Install snipe dependencies
  command: php composer.phar install --no-dev --prefer-source
  args:
    chdir: "{{ snipe_install_dir }}"
    creates: "{{ snipe_install_dir }}/vendor"
    warn: no
  become: true

- name: Snipe install | Generate app_key
  command: php artisan key:generate --force
  args:
    chdir: "{{ snipe_install_dir }}"
    warn: no
  become: true

- name: Snipe install | Clear cached config
  command: php artisan config:clear
  args:
    chdir: "{{ snipe_install_dir }}"
    warn: no
  become: true

- name: Snipe install | Copy updated nginx site config
  template:
    src: snipeit.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
  become: true
